service: lambda-tiler

provider:
  name: aws
  runtime: python3.6
  profile: palm
  region: 'us-east-1'
  role: arn:aws:iam::838255262149:role/lambda_basic_execution
  deploymentBucket: palm-risk-poc
  iamRoleStatements:
    - Effect: "Allow"
      Action:
         - "s3:*"
      Resource:
         - 'arn:aws:s3:::palm-risk-poc'
  environment:
    GDAL_CACHEMAX: 75%
    GDAL_TIFF_OVR_BLOCKSIZE: 512
    VSI_CACHE: TRUE
    VSI_CACHE_SIZE: 536870912
    GDAL_DISABLE_READDIR_ON_OPEN: true

custom:
  apigwBinary:
    types:
      - '*/*'

plugins:
  - serverless-apigw-binary

package:
  artifact: package.zip

functions:
  lambda-tiler:
    handler: app.handler.APP
    memorySize: 1536
    timeout: 20
    events:
      - http:
          path: /{proxy+}
          method: get
          cors: true
